name: Migrate Kernel Source to GKI

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Kernel Repo URL'
        required: true
      repo_branch:
        description: 'Branch of Kernel repo'
        required: true
      device:
        description: 'Device code (e.g., Xperia XZ3: akatsuki)'
        required: true
      gki_branch:
        description: 'New branch for GKI kernel source'
        required: true

env:
  REPO_BRANCH: android-14
  TZ: Asia/Shanghai
  ARCH: arm64
  SUBARCH: arm64
  XZ3_DEVICE: akatsuki
  XZ3_DEFCONFIG: tama_akatsuki_defconfig

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Create workdir
      run: |
        mkdir -p /workdir

    - name: Clone kernel source
      working-directory: /workdir
      run: |
        git clone --depth=1 ${{ github.event.inputs.repo }} -b ${{ github.event.inputs.repo_branch }} kernel

    - name: Migrate kernel source to GKI
      working-directory: /workdir/kernel
      run: |
        # Apply GKI patches from Google sources
        git am https://android.googlesource.com/kernel/common/+refs/heads/android-14/patches/*.patch
        # Update kernel config
        cp arch/arm64/configs/tama_akatsuki_defconfig .config
        # Update kernel source
        git add .
        git commit -m "Migrated kernel source to GKI"

    - name: Create new branch for GKI kernel source
      working-directory: /workdir/kernel
      run: |
        git checkout -b ${{ github.event.inputs.gki_branch }}

    - name: Push changes to new branch
      working-directory: /workdir/kernel
      run: |
        git push origin ${{ github.event.inputs.gki_branch }}
